# J.R. Romero, A. Ramírez, A. Fuentes-Almoguera, C. García.
# "Automated machine learning for test case prioritisation".
# 2024.

# Script used to create the lineplot of the algorithm analysis
# Uses the .csv files generated by algorithm_analysis_versions.py

import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

curdir = os.path.dirname(os.path.abspath(__file__))

# Folder where the results are stored
results_folder = 'algorithm_analysis_1seed_auc_reduce_25_25'

executions = ['1', '2', '3', '4', '5']

# Algorithm to analyze, either preprocessing (e.g. SMOTE) or classification (e.g. RandomForestClassifier)
algorithm = 'SMOTE'

# Datasets to plot
datasets = ['Angel-ML@angel', 'apache@logging-log4j2', 'apache@sling', 'eclipse@paho.mqtt.java', 'optimatika@ojAlgo', 'zolyfarkas@spf4j']

# Plot the results
for e in executions:
    data = pd.read_csv(os.path.join(curdir, results_folder, f'{algorithm}_{e}.csv'))
    tmp = list(set(data.columns).intersection(set(datasets)))

    if len(tmp) == 0:
        print('Trying to plot datasets that are not in the results')
        continue

    plt.figure(figsize=(10, 10))
    sns.set_theme(style="darkgrid")
    sns.lineplot(data=data[tmp])
    plt.xlabel('Version')
    plt.ylabel('Percent of occurrences')
    plt.title(f'{algorithm} occurrences in the dataset')
    plt.savefig(os.path.join(curdir, results_folder, f'{algorithm}_{e}.png'))
    plt.close()