# J.R. Romero, A. Ramírez, A. Fuentes-Almoguera, C. García.
# "Automated machine learning for test case prioritisation".
# 2024.

# Script used to create the heatmaps of the classification and preprocess algorithms over the 5 seeds
# Uses the .csv files generated by algorithms_heatmap.py

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

curdir = os.path.dirname(os.path.abspath(__file__))
curdir = os.path.abspath('.')

executions = ['1', '2', '3', '4', '5']
seeds = {
    '1': 123,
    '2': 897,
    '3': 564,
    '4': 000,
    '5': 789
}

data = []
for e in executions:
    data.append(pd.read_csv(os.path.join(curdir, f'classification_algorithms_{e}.csv'), index_col='algorithm'))

data = pd.concat(data)
data = data.groupby(data.index)
data = data.mean()
data = data.round(3)
plt.figure(figsize=(40, 20))
plt.title(f'Classification algorithms heatmap')
sns.heatmap(data, annot=True, cmap='Blues', fmt='g')
plt.savefig('classification_algorithms.png', bbox_inches='tight')
plt.close()


data = []
for e in executions:
    data.append(pd.read_csv(os.path.join(curdir, f'preprocess_algorithms_{e}.csv'), index_col='algorithm'))
    
data = pd.concat(data)
data = data.groupby(data.index)
data = data.mean()
data = data.round(3)
plt.figure(figsize=(40, 20))
plt.title(f'Preprocess algorithms heatmap seed')
sns.heatmap(data, annot=True, cmap='Blues', fmt='g')
plt.savefig('preprocess_algorithms.png', bbox_inches='tight')
plt.close()
